# Generated by Django 4.2.7 on 2024-01-17 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='rang1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.color'),
            preserve_default=False,
        ),
    ]
