# Generated by Django 4.2.7 on 2024-01-17 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_color_products_size_products_rang1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'Rang'},
        ),
        migrations.AddField(
            model_name='products',
            name='userr',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
