# Generated by Django 4.2.7 on 2024-01-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_color_options_products_userr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='userr',
        ),
    ]
