# Generated by Django 4.2.7 on 2024-01-17 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_coment_userr'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='pro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.products'),
            preserve_default=False,
        ),
    ]
