# Generated by Django 5.0.1 on 2024-01-19 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_products_name_en_products_name_ru_products_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='rang1_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.color'),
        ),
        migrations.AddField(
            model_name='products',
            name='rang1_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.color'),
        ),
        migrations.AddField(
            model_name='products',
            name='rang1_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.color'),
        ),
    ]
