# Generated by Django 5.0.1 on 2024-01-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_products_description_en_products_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='products',
            name='rang1_en',
        ),
        migrations.RemoveField(
            model_name='products',
            name='rang1_ru',
        ),
        migrations.RemoveField(
            model_name='products',
            name='rang1_uz',
        ),
    ]
