# Generated by Django 5.0.1 on 2024-01-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_products_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='rang_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='rang_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='rang_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description_uz',
            field=models.TextField(null=True),
        ),
    ]
