# Generated by Django 4.1.7 on 2024-01-27 11:22

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=builtins.print, max_length=254),
            preserve_default=False,
        ),
    ]
